### ISSUE TITLE
Merge 0.8-dev to master

### ISSUE THREAD

**Issue by soininen** [spine-tools/Spine-Toolbox#2692]
Plan to merge `0.8-dev` to `master`:

- [x] Ensure `CHANGELOG.md` is up-to-date (#2693, spine-tools/Spine-Database-API#386)
- [x] Show Upgrade notification window on Toolbox startup to users in `master` (just once) (#2699)
- [x] Release hopefully last 0.7.x to PyPI (#2694)
- [x] Give a short grace period until **2024-04-29**
- [x] Make release branches for 0.7.x in all four repositories, update `requirements.txt` to pull from other release branches
~- [ ] Revert `master` back to `last-merged-to-entity-branch` tag so as to minimize merge conflicts in all four repositories~
- [x] Merge `0.8-dev` to `master` in all four repositories, resolve merge conflicts (see @PekkaSavolainen's post below) 
- [x] Make sure `requirements.txt` points again to `master`, not `0.8-dev`
- [x] Make sure the Upgrade notification is gone from 0.8
~- [ ] Close eyes, hope for the best~ We are not descended from fearful men.
- [x] Release 0.8 to PyPI (remember to update `CHANGELOG.md`)
- [x] Update Bundle generation (#2720)
- [x] Update Downloads page (spine-tools/Downloads#1)

Edit: dropped the "Revert `master`" step according to the discussion below.

**Comment by PekkaSavolainen** [comment]
I tested merging in my **fork** repos. I merged the latest commit from 0.8-dev to master (just like we merge feature branches), then solved all conflicts based on what was in 0-8-dev branch. There were only about 10 files in spine-toolbox and spine-items that needed conflict resolution, less than 10 files in both spine-engine and spinedb-api. Then I just fixed the requirements.txt in both spine-toolbox and spine-items to point to master again, fixed some repo paths in github actions and voilá. All tests passed on the first try and the app seems to be working fine. There was some traceback related to the cat animation but I'm not sure if this has something to do with a brand new PySide6 version (6.7.0). On second try I could not reproduce the traceback anymore. If you want to try master after 0.8-dev has been merged, clone Spine-Toolbox from my personal stash and do `pip install -r requirements.txt` in a conda or venv.

**Comment by soininen** [comment]
> I tested merging in my fork repos.

@PekkaSavolainen Thank you so much for the test! Sounds like we can omit the revert step and just merge as usual.

**Comment by soininen** [comment]
Merging PR #2701 ticks the second box in the task list.

**Comment by soininen** [comment]
#2725 needs to be fixed before we can proceed with this. I am working on it.

**Comment by soininen** [comment]
I will fix #2723 before releasing 0.8 to PyPI.

**Comment by soininen** [comment]
With the release of 0.8.0 we are done here.
